# version: "3.8"
services:
  postgresDB:
    image: postgres:14.1
    #container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: db_crudpos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql_db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: db_crud
  #     MYSQL_USER: Legacy_crud
  #     MYSQL_PASSWORD: root
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   ports:
  #     - "3307:3306"